## This config file mixes Climate configs and your personnal configs.
##
## You can add a config then get it in the code. 
## e.g if you create the config named "enableWord" you can get it from the code on this way : Climate\Config::enableWord()
---

# Name of the application
applicationName: Climate
# Version of the application
applicationVersion: 0.1



#####################################
#  PLACE FOR YOR PERSONNAL CONFIGS  #
#####################################









#####################
#  CLIMATE CONFIGS  #
#####################


# run log file
# Every time a script ends and log will be written here
# Can be relative (root of the application) or absolute (root or the system) path
# --
# It is adviced to set the logs into the logs of the system. E.g for linux it will be /var/log/myappname/access.log
accessLog: log/access.log

# error log file
# Every time an error or an exception stops the script, the ouput is loggued here
# Can be relative (root of the application) or absolute (root or the system) path
# --
# It is adviced to set the logs into the logs of the system. E.g for linux it will be /var/log/myappname/error.log
errorLog: log/error.log

# Send email on error 
# yes|no
# mail client must bust configured
sendEmailOnError: yes

# Send email to
sendEmailOnErrorTo: me@mydomaine.tld

# Path of the route file
# It is a yaml file
# Can be relative path (root of the application) or absolute path (root of the system) 
routesFile: application/routes.yml

# set to yes to go oon debugRoutes mode.
# debugRoutes mode allow to type a command and see how it is routed without launching the application
# Note that while debugRoutes mode is enabled the application wont launch anything, just give an output of the routing
# Possible values : yes|no
debugRoutes: no
